//urlhttp://servicosbhtrans.pbh.gov.br/bhtrans/bhtmobile/app_itinerario5b.asp?linha=S50&nome=CAICARA%20/%20NOVA%20VISTA%20VIA%20UFMG&saindo=CAICARA&nomsubl=PRINCIPAL&tipo=RUA&logradouro=VILA%20RICA&numero=1315
var bhTrans50Initi = "RUA+VILA+RICA,+1315,+Belo+Horizonte+-+Minas+Gerais";
//var extraPoint = '19°51\'47.4"S+43°57\'55.8"W';
//var extraPoint = 'R.+11+-+Novo+Aarão+Reis+Belo+Horizonte+-+MG'
var bhTransResult = "RUA+HENRIQUE+GORCEIX+1790+Belo+Horizonte+-+Minas+Gerais+to:RUA+BELMIRO+BRAGA+1195+Belo+Horizonte+-+Minas+Gerais+to:RUA+BARAO+DE+COROMANDEL+50+alto+caiçaras+Belo+Horizonte+-+Minas+Gerais+to:RUA+ALABANDINA+180+Belo+Horizonte+-+Minas+Gerais+to:RUA+RENATO+NASCIMENTO+490+Belo+Horizonte+-+Minas+Gerais+to:AVE+DEL+REY+145+Belo+Horizonte+-+Minas+Gerais+to:AVE+PRESIDENTE+CARLOS+LUZ+2800+Belo+Horizonte+-+Minas+Gerais+to:AVE+ANTONIO+ABRAHAO+CARAM+853+Belo+Horizonte+-+Minas+Gerais" +"to:Professor+Baeta+Viana-330+to:Professor+Giorgio+Schreiber+-+140+to:RUA+REITOR+PIRES+DE+ALBUQUERQUE+100+Belo+Horizonte+-+Minas+Gerais+to:RUA+E+525+Belo+Horizonte+-+Minas+Gerais+to:AVE+MENDES+PIMENTEL+775+Belo+Horizonte+-+Minas+Gerais+to:AVE+PRESIDENTE+ANTONIO+CARLOS+6387+Belo+Horizonte+-+Minas+Gerais+to:AVE+BERNARDO+DE+VASCONCELOS+210+Belo+Horizonte+-+Minas+Gerais+to:AVE+BERNARDO+DE+VASCONCELOS+1334+Belo+Horizonte+-+Minas+Gerais+to:AVE+CRISTIANO+MACHADO+2939+Belo+Horizonte+-+Minas+Gerais+to:AVE+CRISTIANO+MACHADO+1911+Belo+Horizonte+-+Minas+Gerais+to:AVE+JOSE+CANDIDO+DA+SILVEIRA+330+Belo+Horizonte+-+Minas+Gerais+to:AVE+JOSE+CANDIDO+DA+SILVEIRA+2530+Belo+Horizonte+-+Minas+Gerais+to:RUA+MARCELINO+FERREIRA+526+Belo+Horizonte+-+Minas+Gerais+to:RUA+CONTAGEM+2103+Belo+Horizonte+-+Minas+Gerais+to:RUA+CONTAGEM+1167+Belo+Horizonte+-+Minas+Gerais+to:+DIAS+PEREIRAS+155+Belo+Horizonte+-+Minas+Gerais";

 /*//from site
var bhTransResult = "RUA+HENRIQUE+GORCEIX+1790+Belo+Horizonte+-+Minas+Gerais+to:RUA+BELMIRO+BRAGA+1195+Belo+Horizonte+-+Minas+Gerais+to:RUA+BARAO+DE+COROMANDEL+50+Belo+Horizonte+-+Minas+Gerais+to:RUA+ALABANDINA+180+Belo+Horizonte+-+Minas+Gerais+to:RUA+RENATO+NASCIMENTO+490+Belo+Horizonte+-+Minas+Gerais+to:AVE+DEL+REY+145+Belo+Horizonte+-+Minas+Gerais+to:AVE+PRESIDENTE+CARLOS+LUZ+2800+Belo+Horizonte+-+Minas+Gerais+to:AVE+ANTONIO+ABRAHAO+CARAM+853+Belo+Horizonte+-+Minas+Gerais+to:RUA+PROFESSOR+BAETA+VIANA+330+Belo+Horizonte+-+Minas+Gerais+to:RUA+PROFESSOR+GIORGIO+SCHREIBER+140+Belo+Horizonte+-+Minas+Gerais+to:RUA+REITOR+PIRES+DE+ALBUQUERQUE+100+Belo+Horizonte+-+Minas+Gerais+to:RUA+E+525+Belo+Horizonte+-+Minas+Gerais+to:AVE+MENDES+PIMENTEL+775+Belo+Horizonte+-+Minas+Gerais+to:AVE+PRESIDENTE+ANTONIO+CARLOS+6387+Belo+Horizonte+-+Minas+Gerais+to:AVE+BERNARDO+DE+VASCONCELOS+210+Belo+Horizonte+-+Minas+Gerais+to:AVE+BERNARDO+DE+VASCONCELOS+1334+Belo+Horizonte+-+Minas+Gerais+to:AVE+CRISTIANO+MACHADO+2939+Belo+Horizonte+-+Minas+Gerais+to:AVE+CRISTIANO+MACHADO+1911+Belo+Horizonte+-+Minas+Gerais+to:AVE+JOSE+CANDIDO+DA+SILVEIRA+330+Belo+Horizonte+-+Minas+Gerais+to:AVE+JOSE+CANDIDO+DA+SILVEIRA+2530+Belo+Horizonte+-+Minas+Gerais+to:RUA+MARCELINO+FERREIRA+526+Belo+Horizonte+-+Minas+Gerais+to:RUA+CONTAGEM+2103+Belo+Horizonte+-+Minas+Gerais+to:RUA+CONTAGEM+1167+Belo+Horizonte+-+Minas+Gerais+to:+DAS+PEREIRAS+155+Belo+Horizonte+-+Minas+Gerais";
*/
